apiVersion: v2
name: ingress
description: A Helm chart for Ingress Controller
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/faisalbasha1982/k8s-helm-helmfile/tree/master/helm
maintainers:
  - name: Faisal Bin Basha
    url: https://github.com/faisalbasha1982
dependencies:
  - name: nginx-ingress
    version: 1.36.0
    repository: https://kubernetes-charts.storage.googleapis.com/